# -*- coding: utf-8 -*-
"""toyota.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NoHngizoEPYUmqvwjX3wzC_Z3sMM-lqv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
files.upload()

# -------------------------
# 1️⃣ Load Dataset
# -------------------------
df = pd.read_csv("Toyota.csv")

print("\n🔹 Head:")
print(df.head())

print("\n🔹 Info:")
print(df.info())

print("\n🔹 Missing Values:")
print(df.isnull().sum())

# -------------------------
# 2️⃣ Handle Missing Values (Numerical: Age)
# -------------------------
df["Age"] = df["Age"].fillna(df["Age"].median())

# -------------------------
# 3️⃣ Handle Missing Values (Categorical: FuelType, MetColor)
# -------------------------
df["FuelType"] = df["FuelType"].fillna(df["FuelType"].mode()[0])
df["MetColor"] = df["MetColor"].fillna(df["MetColor"].mode()[0])

print("\n🔹 Missing Values After Filling:")
print(df.isnull().sum())

# -------------------------
# 4️⃣ Rename Columns (Standardization)
# -------------------------
df.rename(columns={
    "Price": "SellingPrice",
    "FuelType": "Fuel",
    "Automatic": "Auto",
    "HP": "HorsePrice"
}, inplace=True)

# -------------------------
# 5️⃣ Convert Data Types
# -------------------------
df["Age"] = df["Age"].astype(int)
df["SellingPrice"] = df["SellingPrice"].astype(float)
df["Fuel"] = df["Fuel"].astype("category")

# -------------------------
# 6️⃣ Clean KM Column
# -------------------------
df["KM"] = df["KM"].replace(["....", "??", "?", "---"], np.nan)
df["KM"] = pd.to_numeric(df["KM"], errors="coerce")
df["KM"] = df["KM"].fillna(df["KM"].median())
df["KM"] = df["KM"].astype(int)

# -------------------------
# 7️⃣ Clean HorsePower Column
# -------------------------
df["HorsePrice"] = df["HorsePrice"].replace(["????","?","...","---"], np.nan)
df["HorsePrice"] = pd.to_numeric(df["HorsePrice"], errors="coerce")
df["HorsePrice"] = df["HorsePrice"].fillna(df["HorsePrice"].median())
df["HorsePrice"] = df["HorsePrice"].astype(int)

# -------------------------
# 8️⃣ Clean CC, Doors, Weight, Auto
# -------------------------
cols = ["CC", "Doors", "Weight"]

for col in cols:
    df[col] = df[col].replace(["???","?","...","---"], np.nan)
    df[col] = pd.to_numeric(df[col], errors="coerce")
    df[col] = df[col].fillna(df[col].median())
    df[col] = df[col].astype(int)

# Auto is categorical → use mode
df["Auto"] = df["Auto"].replace(["???","?","...","---"], np.nan)
df["Auto"] = df["Auto"].fillna(df["Auto"].mode()[0])
df["Auto"] = df["Auto"].astype(int)

# -------------------------
# 9️⃣ Grouping & Sorting
# -------------------------
print("\n🔹 Average Selling Price by Fuel Type:")
print(df.groupby("Fuel")["SellingPrice"].mean())

print("\n🔹 Count of Cars by Fuel Type:")
print(df.groupby("Fuel")["Fuel"].count())

print("\n🔹 Average KM by Auto Transmission:")
print(df.groupby("Auto")["KM"].mean())

print("\n🔹 Mean Selling Price & KM by Fuel Type:")
print(df.groupby("Fuel")[["SellingPrice", "KM"]].mean())

print("\n🔹 Sorted by Selling Price (Low to High):")
print(df.sort_values("SellingPrice"))

print("\n🔹 Sorted by Selling Price (High to Low):")
print(df.sort_values("SellingPrice", ascending=False))

print("\n🔹 Sorted by KM:")
print(df.sort_values("KM"))

print("\n🔹 Sort by Fuel then Price:")
print(df.sort_values(["Fuel", "SellingPrice"], ascending=[True, False]))



plt.plot(df["Age"], df["SellingPrice"])
plt.xlabel("Age")
plt.ylabel("Selling Price")
plt.title("Age vs Selling Price")
plt.show()

df["Fuel"].value_counts().plot(kind="bar")
plt.title("Fuel Type Count")
plt.show()

df["Fuel"].value_counts().plot(kind="pie", autopct="%1.1f%%")
plt.title("Fuel Type Distribution")
plt.show()

plt.scatter(df["KM"], df["SellingPrice"])
plt.xlabel("KM")
plt.ylabel("Selling Price")
plt.title("KM vs Selling Price")
plt.show()